// AUTOGENERATED FILE
// This file was generated from DialogueParser.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface DialogueActionDict<T> extends BaseActionDict<T> {
  DialogueData?: (this: NonterminalNode, arg0: IterationNode) => T;
  String?: (this: NonterminalNode, arg0: IterationNode) => T;
  StringVar?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Number?: (this: NonterminalNode, arg0: IterationNode) => T;
  NumberVar?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Vector?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: NonterminalNode, arg6: TerminalNode) => T;
  StringVarEq?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  NumberVarEq?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  StringVarNeq?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  NumberVarNeq?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  VarLt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  VarLte?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  VarGt?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  VarGte?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Conditional?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  MoveToNode?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Node?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode, arg3: TerminalNode) => T;
  Line?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Line_condition?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode, arg4: NonterminalNode) => T;
  Options?: (this: NonterminalNode, arg0: IterationNode) => T;
  OptionLine?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  OptionLine_condition?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: NonterminalNode) => T;
  Cmd?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Cmd_condition?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Command?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  SetStringVar?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  SetNumberVar?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  MoveCam?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  StartCombat?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
}

export interface DialogueSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: DialogueActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: DialogueActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: DialogueActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: DialogueActionDict<T>): this;
}

export interface DialogueGrammar extends Grammar {
  createSemantics(): DialogueSemantics;
  extendSemantics(superSemantics: DialogueSemantics): DialogueSemantics;
}

declare const grammar: DialogueGrammar;
export default grammar;

